// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("140.612")]
[assembly: AssemblyFileVersion("140.612")]
[assembly: AssemblyInformationalVersion("140.612+48b03e3")]
