// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System.Reflection;
[assembly: AssemblyVersion("140.0.499")]
[assembly: AssemblyFileVersion("140.0.499")]
[assembly: AssemblyInformationalVersion("140.0.499+dc786be")]
